name: Deploy Gorecipe to Production

on:
  push:
    branches:
      - main

jobs:

  deploy_production:
    runs-on: ubuntu-latest
    environment: Dreamhost VPS Production
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run:  make dist
      env:
        DB_DSN: ${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@tcp(${{ secrets.DB_HOST }})/${{ secrets.DB_NAME }}
        DEBUG: false
        DB_DIALECT: mysql
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}

    - name: Deploy to Production VPS
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          ARGS: '-rltgoDzvO --delete'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: 'dist'
          TARGET: 'gorecipes'

    - name: Launch Gorecipe Daemon
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: killall gorecipes; killall screen; cd /home/${{ secrets.REMOTE_USER }}/gorecipes/dist/; screen -dm ./gorecipes --config gorecipes.conf
