name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - run: go get -v github.com/dgrijalva/jwt-go
    - run: go get -v github.com/go-sql-drive/mysql
    - run: go get -v github.com/gorilla/mux
    - run: go get -v github.com/jmoiron/sqlx
    - run: go get -v github.com/mattn/go-sqlite3
    - run: go get -v github.com/rs/cors

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

#  deploy:
#    runs-on: ubuntu-latest
#    needs: [build]
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
#    steps:
#    - uses: actions/checkout@v2
#    - name: Deploy to Server
#    - uses: easingthemes/ssh-deploy@v2.1.5
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#        ARGS: '-rltgoDzvO --delete'
#        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#        REMOTE_USER: ${{ secrets.REMOTE_USER }}
