name: Go

on:
  push:
    branches:
      - staging
      - workflow_setup
  pull_request:
    branches: [ staging ]

jobs:

  deploy_staging:
    runs-on: ubuntu-latest
    environment: Dreamhost VPS Staging
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/workflows/build.yml
    - name: Deploy to Staging VPS

      #TODO: I actually want to copy the binary, config files, and the bootstrapping directories, specifically
      #TODO: instead of including config files in the deploy, maybe write them using the env secrets here?
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          ARGS: '-rltgoDzvO --delete'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: 'gorecipes'
      #TODO: define a "run server" action and use it here.
